swagger: "2.0"
info:
  description: "Concesionario."
  version: "1.0.0"
  title: "Concesionario"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "coche"
  description: "Coches del concesionario"
- name: "marca"
  description: "Marcas de los coches"


paths:
  /marcas:
    get:
      tags:
      - "marca"
      summary: "Listado de marcas"
      description: "Listado de todos las marcas"
      operationId: "obtenerTodos"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "Operacion exitosa"
          schema:
            $ref: "/cursos"
        "400":
          description: "No se encuentra"
        "404":
          description: "No se encuentra"





  /coche:
    post:
      tags:
      - "coche"
      summary: "Insertar coche"
      description: ""
      operationId: "insertar"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "operacion exitosa"
          schema:
            $ref: "/resenyas"
        "400":
          description: "Coche invalido"
          
  /coche/{id}:
    get:
      tags:
      - "coche"
      summary: "Encontrar coches por id de marca"
      description: "Devuelve coches por marca"
      operationId: "obtenerPorMarca"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id de la marca del coche"
        required: true
        type: "long"
        format: "int64"
      responses:
        "200":
          description: "operación exitosa"
          schema:
            $ref: "/coches/{1}"
        "400":
          description: "Id no valida"
        "404":
          description: "Coches de la marca no encontrados"
 

definitions:
  Coche:
    type: "object"
    properties:
      id:
        type: "long"
        format: "int64"
      modelo:
        type: "string"
      matricular:
        type: "string"
      marca_id:
        type: "long"
        format: "int64"
    xml:
      name: "Coche"
      
  Marca:
    type: "object"
    properties:
      id:
        type: "long"
        format: "int64"
      nombre:
        type: "string"


    xml:
      name: "Marca"