openapi: 3.0.1
info:
  title: MarcaREST
  description: Servicio Rest para altas de coches
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/'
    description: Servidor de Spring Boot
    variables: {}
paths:

        
  /alta:
    post:
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coche'
      responses:
        '201':
          description: Creado
        '400':
           description: Petición incorrecta
components:
  schemas:
    Marca:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        apellidos:
          type: string