openapi: 3.0.1
info:
  title: MarcaREST
  description: REST de listado
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/'
    description: Servidor de Spring Boot
    variables: {}
paths:
  '/marcas/{id}':
    get:
      summary: Obtener un marca por id con coches
      operationId: getById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Devuelve el marca cuyo id es el que se ha pedido, y los coches de esa marca
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Marca'
        '404':
          description: No encontrado

        
components:
  schemas:
    Marca:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        apellidos:
          type: string